reorg; cleanp; and word count

diff --git a/s/default b/s/default
--- a/s/default
+++ b/s/default
@@ -1,22 +1,25 @@
 #!/bin/bash
+#
 #--
 #
 # Purpose: handles student missions on matrix
 # Creator: Mark Fernandes.
 # Created: March 25, 2020
-# Updated: March 29, 2020
+# Updated: June 16, 2023
 # License: MIT
 
 OWNER=mark.fernandes
-RIDER=                  # student log files
-TOKEN=                  # mission (test/quiz)
+LOGSD=                  # dir for log files
+ITEM=                   # context specific item (section/test/quiz)
+TOPIC=                  # topic/section of paper (if any)
+WORDS=                  # word count of item
 
 MAILER=                 # ${OWNER}@owner.domain
 REPLIER=                # ${USER}@MyOwner.domain
 
 THISDIR=`dirname $(readlink -e $0)`
-[[ -e ${THISDIR}/local.default ]] && . ${THISDIR}/local.default
-if [[ -z ${OWNER} || -z ${RIDER} || -z ${TOKEN} || -z ${MAILER} || -z ${REPLIER} ]]; then
+[[ -e ${THISDIR}/local.default ]] &&  . ${THISDIR}/local.default
+if [[ -z ${OWNER} || -z ${LOGSD} || -z ${ITEM} || -z ${MAILER} || -z ${REPLIER} ]]; then
   echo "nothing to do." >&2
   exit 1
 fi
@@ -25,12 +28,12 @@ fi
 # normal use should not need modifications below this line
 #--
 TIMESTAMP=$(/usr/bin/date +"%Y%m%d_%H:%M%S")
-logF=${USER}-${TIMESTAMP}
+[[ -z ${TOPIC} ]] && logF=${USER}-${TIMESTAMP} || logF=${USER}-${TOPIC}-${TIMESTAMP}
 
-if [[ -d /home/${OWNER}/.neo/${RIDER} ]]; then
-    cd /home/${OWNER}/.neo/${RIDER}
+if [[ -d /home/${OWNER}/.neo/${LOGSD}/${ITEM} ]]; then
+    cd /home/${OWNER}/.neo/${LOGSD}/${ITEM}
 else
-   echo -e "\nERROR: /home/${OWNER}/.neo/${RIDER} not found." >&2
+   echo -e "\nERROR: neo cannot save your results. Email ${MAILER} with this error message.\n" >&2
    exit 1
 fi
 /usr/bin/touch ${logF}
@@ -41,49 +44,50 @@ if [[ -d all ]]; then
   /usr/bin/chmod 060 all/${logF}-00
 fi
 
-echo -n "Checking your session..." >&2
-if [[ "$USER" != "$OWNER" ]]; then
-  if [[ -e /usr/local/bin/mwho && `/usr/local/bin/mwho | /usr/bin/grep -ce $USER` -ne 1 ]]; then
-    echo -e "\nERROR: Only ONE login session allowed. Logout or kill your other login sessions." >&2
-    exit 1
-  fi
+# get entire paper or sub-section if it exists
+if [[ -d /home/${OWNER}/${VAULT} && -f /home/${OWNER}/${VAULT}/${TOPIC} ]]; then
+  WORDS=$(/usr/bin/wc -w /home/${OWNER}/${VAULT}/${TOPIC}| /usr/bin/cut -d' ' -f1)
+  /usr/bin/cat /home/${OWNER}/${VAULT}/${TOPIC} >> ${logF}
+else
+  echo >> ${logF}
 fi
-echo "Ok!" >&2
 
-echo "Full Name: " >> ${logF}
-echo >> ${logF}
-[[ -e /home/${OWNER}/t/${TOKEN} ]] && /usr/bin/cat /home/${OWNER}/t/${TOKEN} >> ${logF}
+if [[ -d all ]]; then
+  /usr/bin/cp ${logF} all/${logF}-01
+  /usr/bin/chmod 060 all/${logF}-01
+fi
 
-l=/usr/local/bin/nled
 echo "What editior do you wish to edit with? Your choices are:" >&2
 #echo "     (e)macs" >&2
-[[ -e $l ]] && echo "     n(l)ed" >&2
 echo "     (n)ano" >&2
 echo "     (v)im"  >&2
-read -p  "Your choice n or v: " editor
+read -p  "Your choice n or  v: " editor
 
 case ${editor} in
     #e) /usr/bin/emacs ${logF} ;;
-    l) /usr/local/bin/nled ${logF} ;;
     n) /usr/bin/nano ${logF} ;;
     v) /usr/bin/vim ${logF} ;;
-    *) { [[ -e $l ]] && $l ${logF} || echo "ERROR! Did not find your editor" >&2 ; exit 1; } ;;
+    *) echo "ERROR! Did not find your editor." >&2 ; exit 1 ;;
 esac
 
 if [[ -d all ]]; then
-  /usr/bin/cp ${logF} all/
-  /usr/bin/chmod 660 all/${logF}
+  /usr/bin/cp ${logF} all/${logF}
+  /usr/bin/chmod 060 all/${logF}
 fi
 
 echo >&2
 
-echo $USER|/usr/bin/grep -e "\." 2>&1 > /dev/null
-if [[ $? -eq 0 ]]; then
-  f=$(echo ${MAILER} | /usr/bin/sed 's/'"${OWNER}"'//')
-  /usr/bin/mail -s "${RIDER}-${TOKEN}: ${USER}" -S replyto="$USER$f" $USER$f < ${logF} 2>/dev/null
+if [[ -n "${FELLOW}" ]]; then
+  echo $USER|/usr/bin/grep -e "\." 2>&1 > /dev/null
+  if [[ $? -eq 0 ]]; then
+    f=$(echo ${MAILER} | /usr/bin/sed 's/'"${OWNER}"'//')
+    /usr/bin/mail -s "${LOGSD}-${ITEM} ${TOPIC}: ${USER}" -S replyto="$USER$f" $USER$f < ${logF} 2>/dev/null
+  fi
 fi
 
-/usr/bin/mail -s "${RIDER}-${TOKEN}: ${USER}" -S replyto="${REPLIER}" ${MAILER} < ${logF} 2>/dev/null
+WORDS=$(echo $(( $(/usr/bin/wc -w ${logF}| /usr/bin/cut -d' ' -f1) - $(echo $WORDS))))
+/usr/bin/mail -s "${LOGSD}-${ITEM} ${TOPIC}: ${USER}" -S replyto="${REPLIER}" ${MAILER} < ${logF} 2>/dev/null
+echo -e "Your submission\n\n\t with approximately $WORDS of your own words\n\t on `date`\n\n was successful." | /usr/bin/mail -s "${LOGSD}-${ITEM}: ${USER}" -S replyto="${REPLIER}" ${REPLIER} ${MAILER} 2>/dev/null
 
 if [[ $? -eq 0 && -s ${logF} ]];
 then
