stop scary abstraction leaks

diff --git a/s/default b/s/default
--- a/s/default
+++ b/s/default
@@ -5,7 +5,7 @@
 # Purpose: handles student missions on matrix
 # Creator: Mark Fernandes.
 # Created: March 25, 2020
-# Updated: June 16, 2023
+# Updated: Oct 31, 2023
 # License: MIT
 
 OWNER=mark.fernandes
@@ -45,11 +45,12 @@ if [[ -d all ]]; then
 fi
 
 # get entire paper or sub-section if it exists
-if [[ -d /home/${OWNER}/${VAULT} && -f /home/${OWNER}/${VAULT}/${TOPIC} ]]; then
-  WORDS=$(/usr/bin/wc -w /home/${OWNER}/${VAULT}/${TOPIC}| /usr/bin/cut -d' ' -f1)
+if [[ -d /home/${OWNER}/${VAULT} && -r /home/${OWNER}/${VAULT}/${TOPIC} ]]; then
+  WORDS=$(/usr/bin/wc -w /home/${OWNER}/${VAULT}/${TOPIC} | /usr/bin/cut -d' ' -f1)
   /usr/bin/cat /home/${OWNER}/${VAULT}/${TOPIC} >> ${logF}
 else
-  echo >> ${logF}
+  >&2 echo "ERROR! Invalid setup, so nothing to see here."
+  exit 1
 fi
 
 if [[ -d all ]]; then
@@ -67,7 +68,7 @@ case ${editor} in
     #e) /usr/bin/emacs ${logF} ;;
     n) /usr/bin/nano ${logF} ;;
     v) /usr/bin/vim ${logF} ;;
-    *) echo "ERROR! Did not find your editor." >&2 ; exit 1 ;;
+    *) >&2 echo "ERROR! Did not find your editor."; exit 1 ;;
 esac
 
 if [[ -d all ]]; then
