handles first run set up and send updates by email

diff --git a/scr/shWins b/scr/shWins
--- a/scr/shWins
+++ b/scr/shWins
@@ -7,7 +7,7 @@ FIELD=6
 SCORE=
 
 if [ ! -s "${DFILE}" ]; then
-  >&2 echo "Directory not found. ${DFILE}"
+  >&2 echo "File empty or not found: ${DFILE}"
   exit 1
 fi
 
